version: '2'

networks:
  default:
    driver: bridge

services:
  db:
    image: postgres
    build:
      context: ./images/db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin

  api:
    build:
      context: ./images/api/
    networks:
      - default
    environment:
      PG_CONNECTION_STRING: postgres://admin:admin@db:5432/skematik
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      MODE: start
    links:
      - db
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes: 
      - './images/api/src:/api/src'

  php:
    build:
      context: ./images/public/
    ports:
      - "80:80"

  front_server:
    build:
      context: ./images/static_server/
    networks:
      - default
    environment:
      DOMAIN:
    ports:
      - "4000:3000"
    volumes:
      - ./images/static_server/src:/skematik/src
      - ./images/public/:/skematik/src/public
