version: '2'

networks:
  default:
    driver: bridge

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    logging:
      driver: none

  db:
    image: postgres
    build:
      context: ./images/db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      VIRTUAL_HOST: db.localhost

  api:
    build:
      context: ./images/api/
    networks:
      - default
    environment:
      PG_CONNECTION_STRING: postgres://admin:admin@db:5432/skematik
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      MODE: start
      VIRTUAL_HOST: ~api\.(localhost|skematik\.io)
    links:
      - db
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes: 
      - './images/api/src:/api/src'

  front_server:
    build:
      context: ./images/static_server/
    networks:
      - default
    environment:
      VIRTUAL_HOST: ~(?<!api.)(localhost|skematik\.io)
    ports:
      - "4000:4000"
    volumes:
      - ./images/static_server/src:/skematik/src
      - ./images/public/:/skematik/src/public
